Feature/customer.html
LukaszCiaston-coder/team-project-icecream pull request #31
Opened 2023-02-18 11:09 UTC by BarbaraIgnaciuk-Charkiewicz

2023-02-18 11:47 UTC, AnnaWitt commented on src/partials/customer.html
> +<section class="customer">
add container

2023-02-18 13:00 UTC, LukaszCiaston-coder requested changes
delete files main.css and main.css.map

2023-02-18 14:34 UTC, AnnaWitt commented on src/partials/customer.html
> +    <img class="customer__image" alt="customer photo" src="../images/testimonials-desk-x1.png" srcset="/images/testimonials-desk-x2.png 2x, /images/testimonials-desk-x3.png 3x"/>
check srcset source line

2023-02-18 14:47 UTC, LukaszCiaston-coder requested changes
delete files main.css and main.css.map

2023-02-18 14:57 UTC, AnnaWitt approved these changes

2023-02-18 16:04 UTC, BarbaraIgnaciuk-Charkiewicz commented
Usunęłam main.css i main.css.map

2023-02-19 13:22 UTC, AnnaWitt approved these changes

2023-02-19 14:19 UTC, closed without merging