customer.html
LukaszCiaston-coder/team-project-icecream pull request #44
Opened 2023-02-19 13:40 UTC by BarbaraIgnaciuk-Charkiewicz

version19.02

2023-02-19 18:06 UTC, bartoszuq submitted a review, later dismissed
ustawilas rozne zdjecia customerow na rozne gestosci wyswietlania (DPR), a powinno byc jedno glowne zdjecie a zdjecia powinny zmieniac sie kiedy kreci sie tą twoją karuzelą a w zwiazku z tym ze ona sie nie kreci, nie musisz dodawac wiecej niz jednego glownego zdjecia customera

wiec zamiast dodawac inne zdjecia na rozna gestosc to dodaj to samo zdjecie na rozna gestosc

2023-02-19 21:41 UTC, LukaszCiaston-coder requested changes

2023-02-19 21:41 UTC, LukaszCiaston-coder commented on src/sass/partials/_customer.scss
> +@import './global';
not needed

2023-02-20 09:45 UTC, AnnaWitt approved these changes

2023-02-20 09:46 UTC, LukaszCiaston-coder approved these changes

2023-02-20 09:49 UTC, merged